### PR TITLE
changes requested by data team

### PR DESCRIPTION
**Pull request by aaronhans**
Implemented most of the changes requested by data team
Added requestor url parameter which is stored in function config so data is not retrievable by anyone

### CODE REVIEW

**Review by britt-allen — APPROVED** [review]
`item.timestamp = item._ts;`
`delete item._ts;`

Assuming this code runs in order and the timestamp col will be populated before the deletion of ts and its deletion will have no affect on the timestamp col then this all looks good to me! Ty! :)

**Review by jbum — APPROVED** [review]
👀 👍

**Review by britt-allen — APPROVED** [review]
Looks good to me, can we get 30 or 60 days worth of COVID data if not too slow? If 14 is the max we can get before performance is impacted then I am fine to leave things as is.

**Comment by aaronhans** [comment]
bumped to 30, easy to change later if this is fast enough

Let me know when it is ok to deploy this @traintestbritt the requestor url parameter will be required to retrieve data when this is merged

**Review by carterm — COMMENTED** [review]
looks legit

**Pull request merged**
